[package]
name = "leo-lang"
version = "1.0.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "The Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = ["aleo", "cryptography", "leo", "programming-language", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "web-programming"]
include = ["Cargo.toml", "leo", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[lib]
path = "leo/lib.rs"

[[bin]]
name = "leo"
path = "leo/main.rs"

[workspace]
members = [ "ast", "compiler", "gadgets", "input", "linter", "package", "typed", "state"]

[dependencies]
leo-compiler = { path = "./compiler", version = "1.0.0" }
leo-gadgets = { path = "./gadgets", version = "1.0.0" }
leo-input = { path = "./input", version = "1.0.0" }
leo-package = { path = "./package", version = "1.0.0" }
leo-state = { path = "./state", version = "1.0.0" }

snarkos-algorithms = { version = "1.0.0", default-features = false }
snarkos-curves = { version = "1.0.0", default-features = false }
snarkos-errors = { version = "1.0.0", default-features = false }
snarkos-gadgets = { version = "1.0.0", default-features = false }
snarkos-models =  { version = "1.0.0", default-features = false }
snarkos-utilities = { version = "1.0.0" }

clap = { version = "2.33.3" }
colored = { version = "2.0" }
dirs = { version = "3.0.1" }
console = { version = "0.12.0" }
dotenv = { version = "0.15.0" }
env_logger = { version = "0.7" }
from-pest = { version = "0.3.1" }
lazy_static = { version = "1.4.0" }
log = { version = "0.4" }
notify= { version = "4.0.15" }
num-bigint = { version = "0.3" }
rand = { version = "0.7" }
rand_core = { version = "0.5.1" }
reqwest = { version = "0.10.7", features = ["blocking", "json"] }
self_update = { version = "0.19.0", features = ["archive-zip"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
toml = { version = "0.5" }
thiserror = { version = "1.0" }
zip = { version = "0.5" }

[dev-dependencies]
rusty-hook = { version = "0.11.2" }

[features]
default = []
ci_skip = ["leo-compiler/ci_skip"]

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 0
debug-assertions = true
debug = true
