[package]
name = "leo-wasm"
version = "1.2.3"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "WASM interpreter of the Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[lib]
crate-type = [ "cdylib", "rlib" ]

[dependencies.leo-asg]
path = "../asg"
version = "1.2.3"

[dependencies.leo-ast]
path = "../ast"
version = "1.2.3"

[dependencies.leo-parser]
path = "../parser"
version = "1.2.3"

[dependencies.leo-imports]
path = "../imports"
version = "1.2.3"

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.wasm-bindgen]
version = "0.2"
features = [ "serde-serialize" ]

[dev-dependencies.wasm-bindgen-test]
version = "0.3.20"
