[package]
name = "leo-compiler"
version = "1.0.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Compiler of the Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = ["aleo", "cryptography", "leo", "programming-language", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "web-programming"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
leo-ast = { path = "../ast", version = "1.0.0" }
leo-gadgets = { path = "../gadgets", version = "1.0.0" }
leo-input = { path = "../input", version = "1.0.0" }
leo-package = { path = "../package", version = "1.0.0"}
leo-typed = { path = "../typed", version = "1.0.0" }
leo-state = { path = "../state", version = "1.0.0" }

snarkos-curves = { version = "1.0.0", default-features = false }
snarkos-dpc = {  version = "1.0.0", default-features = false }
snarkos-errors = { version = "1.0.0", default-features = false }
snarkos-gadgets = { version = "1.0.0", default-features = false }
snarkos-models =  { version = "1.0.0", default-features = false }
snarkos-objects = { version = "1.0.0", default-features = false }
snarkos-utilities = { version = "1.0.0" }

bincode = { version = "1.0" }
hex = { version = "0.4.2" }
log = { version = "0.4" }
pest = { version = "2.0" }
rand = { version = "0.7" }
rand_xorshift = { version = "0.2", default-features = false }
serde = { version = "1.0" }
sha2 = { version = "0.9" }
thiserror = { version = "1.0" }

[dev-dependencies]
num-bigint = { version = "0.3" }

[features]
default = []
ci_skip = ["leo-ast/ci_skip", "leo-typed/ci_skip"]
