name: Leo Binary Tests
on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'documentation/**'
env:
  RUST_BACKTRACE: 1

jobs:
  new:
    name: Hello Leo ('leo new hello-world')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Install Leo
        uses: actions-rs/cargo@v1
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
        with:
          command: install
          args: --path .

      - name: 'leo new hello-world'
        run: |
          cd ..
          leo new hello-world
          ls -la
          cd hello-world && ls -la
          leo run

  init:
    name: Hello Leo ('leo init')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Install Leo
        uses: actions-rs/cargo@v1
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
        with:
          command: install
          args: --path .

      - name: 'leo init'
        run: |
          cd .. && mkdir hello-world && cd hello-world
          leo init
          ls -la
          leo run
