name: CI
on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'documentation/**'
env:
  RUST_BACKTRACE: 1

jobs:
  fuzz:
    name: Leo Fuzzer ('leo-fuzzer run --random 10')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

#      - name: Install Rust
#        uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: nightly
#          override: true
#          components: rustfmt
#
#      - uses: actions/cache@v2
#        with:
#          path: |
#            ~/.cargo/registry
#            ~/.cargo/git
#            target
#          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
#
#      - name: Install Leo
#        uses: actions-rs/cargo@v1
#        with:
#          command: install
#          args: --path .

      - name: Load the 'leo-fuzzer' deploy key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.LEO_FUZZER_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add -k ~/.ssh/id_rsa

      - name: Install 'leo-fuzzer'
        run: |
          cd .. && git clone ssh://git@github.com/AleoHQ/leo-fuzzer.git --depth=1
          cd leo-fuzzer && cargo install --path .

      - name: Run 'leo-fuzzer'
        run: |
          cd .. && leo-fuzzer run --no-update --no-load --random 10 --r-times 5 --mode random --loop 1
